#!/usr/bin/env python3
import subprocess, sys, os

# Add current directory as MOTH_HOME
env = os.environ.copy()
env["MOTH_HOME"] = "/".join(os.path.realpath(__file__).split("/")[:-1])

# Execute SOMns with the update environment
os.system("./kernan/Grace/grace --ws > /dev/null 2>&1 &")
os.execvpe("./SOMns/debug", sys.argv, env)
os.system("(sh \"pkill -f kernan\" > /dev/null 2>&1)")
