#!/usr/bin/env python3
import subprocess, sys, os

# Add current directory as MOTH_HOME
env = os.environ.copy()
env["MOTH_HOME"] = "/".join(os.path.realpath(__file__).split("/")[:-1])

# Execute SOMns with the update environment
# subprocess.run(["./SOMns/som"] + sys.argv[1:], env=env)
os.execvpe("./SOMns/som", sys.argv, env)
